name: Sync code samples from Aiven Provider for Terraform repository

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Terraform Provider repository
        run: git clone --branch main --depth 1 https://github.com/staceysalamon-aiven/test-terraform-provider-aiven.git temp-terraform-repo

      - name: Extract aiven_organization example usage
        run: |
          # Pull the resource.tf file for creating organizations
          ORGANIZATION_EXAMPLE_USAGE=$(cat temp-terraform-repo/examples/resources/aiven_organization/resource.tf)

          # Replace placeholders in the docs with the example usage
          awk -v code="$ORGANIZATION_EXAMPLE_USAGE" '/<!-- INSERT_ORGANIZATION_UNIT_EXAMPLE_USAGE -->/ {print "<!-- INSERT_ORGANIZATION_UNIT_EXAMPLE_USAGE -->"; print "```hcl"; print code; print "```"; next} 1' docs/tools/aiven-console/howto/create-orgs-and-units.md > docs/tools/aiven-console/howto/create-orgs-and-units.md.tmp
          mv docs/tools/aiven-console/howto/create-orgs-and-units.md.tmp docs/tools/aiven-console/howto/create-orgs-and-units.md

      - name: Extract aiven_organization_project example usage
        run: |
          # Pull the resource.tf file for creating projects
          PROJECT_EXAMPLE_USAGE=$(cat temp-terraform-repo/examples/resources/aiven_organization_project/resource.tf)

          # Replace placeholders in the docs with the example usage
          awk -v code="$PROJECT_EXAMPLE_USAGE" '/<!-- INSERT_ORGANIZATION_PROJECT_EXAMPLE_USAGE -->/ {print "<!-- INSERT_ORGANIZATION_PROJECT_EXAMPLE_USAGE -->"; print "```hcl"; print code; print "```"; next} 1' docs/platform/howto/manage-project.md > docs/platform/howto/manage-project.md.tmp
          mv docs/platform/howto/manage-project.md.tmp docs/platform/howto/manage-project.md

      - name: Extract aiven_pg example files
        run: |
          # Pull the files for the example to create a PostgreSQL service
          PROVIDER=$(cat temp-terraform-repo/examples/postgres/provider.tf)
          SERVICE=$(cat temp-terraform-repo/examples/postgres/service.tf)
          VARIABLES=$(cat temp-terraform-repo/examples/postgres/variables.tf)

          # Add indentation to the code samples
          PROVIDER_INDENTED=$(echo "$PROVIDER" | sed 's/^/   /')
          SERVICE_INDENTED=$(echo "$SERVICE" | sed 's/^/   /')
          VARIABLES_INDENTED=$(echo "$VARIABLES" | sed 's/^/   /')

          # Replace placeholders in the docs with the example usage
          # Check and replace the provider block if necessary
          awk -v code="$PROVIDER_INDENTED" '/<!-- START_POSTGRES_EXAMPLE_PROVIDER -->/ {print $0; in_block=1; next} /<!-- END_POSTGRES_EXAMPLE_PROVIDER -->/ {if (in_block) {print "   ```hcl"; print code; print "   ```"; in_block=0} print $0; next} in_block {next} {print $0}' docs/products/postgresql/get-started.md > docs/products/postgresql/get-started.md.tmp1

          # Check and replace the service block if necessary
          awk -v code="$SERVICE_INDENTED" '/<!-- START_POSTGRES_EXAMPLE_SERVICE -->/ {print $0; in_block=1; next} /<!-- END_POSTGRES_EXAMPLE_SERVICE -->/ {if (in_block) {print "   ```hcl"; print code; print "   ```"; in_block=0} print $0; next} in_block {next} {print $0}' docs/products/postgresql/get-started.md.tmp1 > docs/products/postgresql/get-started.md.tmp2

          # Check and replace the variables block if necessary
          awk -v code="$VARIABLES_INDENTED" '/<!-- START_POSTGRES_EXAMPLE_VARIABLES -->/ {print $0; in_block=1; next} /<!-- END_POSTGRES_EXAMPLE_VARIABLES -->/ {if (in_block) {print "```hcl"; print code; print "```"; in_block=0} print $0; next} in_block {next} {print $0}' docs/products/postgresql/get-started.md.tmp2 > docs/products/postgresql/get-started.md.tmp3

          # Final move to replace the original file with the updated one
          mv docs/products/postgresql/get-started.md.tmp3 docs/products/postgresql/get-started.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add .
          git commit -m "Sync Terraform code samples" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
