name: Sync Terraform Example Usage

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-all-examples:
    uses: ./.github/workflows/reusable-sync-example2.yaml
    with:
      examples: |
        - { name: 'aiven_organization', file: 'aiven_organization/resource.tf', placeholder: 'ORGANIZATION_EXAMPLE_USAGE', doc: 'docs/tools/aiven-console/howto/create-orgs-and-units.md' }
        - { name: 'aiven_organization_project', file: 'aiven_organization_project/resource.tf', placeholder: 'ORGANIZATION_PROJECT_EXAMPLE_USAGE', doc: 'docs/platform/howto/manage-project.md' }
