name: Sync Terraform example usage

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-example:
    uses: ./.github/workflows/reusable-sync-example.yaml
    with:
      example_name: 'aiven_organization'
      example_file: 'aiven_organization/resource.tf'
      placeholder: 'ORGANIZATION_EXAMPLE_USAGE'
      doc_file: 'docs/tools/aiven-console/howto/create-orgs-and-units.md'
    secrets: inherit

  sync-example-2:
    uses: ./.github/workflows/reusable-sync-example.yaml
    with:
      example_name: 'aiven_organizational_unit'
      example_file: 'aiven_organizational_unit/resource.tf'
      placeholder: 'ORGANIZATIONAL_UNIT_EXAMPLE_USAGE'
      doc_file: 'docs/tools/aiven-console/howto/create-orgs-and-units.md'
    secrets: inherit

  sync-example-3:
    uses: ./.github/workflows/reusable-sync-example.yaml
    with:
      example_name: 'aiven_organization_project'
      example_file: 'aiven_organization_project/resource.tf'
      placeholder: 'ORGANIZATION_PROJECT_EXAMPLE_USAGE'
      doc_file: 'docs/platform/howto/manage-project.md'
    secrets: inherit
