name: Update Terraform Provider Submodule
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Submodule
        run: |
          git submodule update --remote --merge
          git add external/terraform-provider
          git commit -m "Auto-update Terraform Provider submodule" || echo "No changes to commit"
          git push
