name: Update Aiven Terraform Provider submodule to sync samples
on:
  schedule:
    - cron: '0 2 * * 1,2,3,4' # Runs at 02:00 every week Mon-Thurs
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Update submodule
        run: |
          # Clean up any submodule issues
          git submodule deinit -f external/terraform-provider
          rm -rf external/terraform-provider
          git submodule update --init --recursive

          # Update the submodule with the latest changes
          git submodule update --remote --merge

          # Add and commit the changes if any
          git add external/terraform-provider
          git commit -m "Sync Terraform samples" || echo "No changes to commit"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: Update Terraform samples
          body: |
            > [!NOTE]
            > Auto-generated PR. Updates the Aiven Provider for Terraform submodule to sync samples.
          base: main
          labels: automated-pr
          branch: terraform-samples-update
          delete-branch: true
